name: CD/CI -- tests


on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - "**"

  workflow_dispatch:


# Run unit tests
# NOTE: Some unit tests regarding imports and import resolution assume that
#       stdlib modules can be resolved -- which is the case with pypy but not
#       with CPython
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "pypy-3.7"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pytest
          python -m pip install --upgrade mock

      - name: Run unit tests
        run: pytest tests/
